#
# Your Crowdin credentials
#
"project_id" : "17"
"api_token" : "763fcd04f64c1312bad530dba993f905bad244a6d8b0e9f8da39bf8589242e3ee16d864c28f71eeb"
"base_path" : "."
"base_url" : "https://supremainc.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true

#
# Files configuration
# i18n/en/docusaurus-plugin-content-docs/current
"files": [
  {
    "source" : "/i18n/en/docusaurus-plugin-content-docs/current/device/xpass_q2/*.mdx",
    "translation" : "/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/device/xpass_q2/%original_file_name%",
    "escape_special_characters": 0,
    "type": "mdx_v1"
  },
  {
    "source" : "/i18n/en/docusaurus-plugin-content-docs/current/device/vionyx/*.mdx",
    "translation" : "/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/device/vionyx/%original_file_name%",
    "escape_special_characters": 0,
    "type": "mdx_v1"
  },
  {
    "source" : "/i18n/en/faqs.json",
    "translation" : "/i18n/%two_letters_code%/%original_file_name%",
    "escape_special_characters": 0,
    "type": "json"
  },
  {
    "source" : "/i18n/en/code.json",
    "translation" : "/i18n/%two_letters_code%/%original_file_name%",
    "escape_special_characters": 0,
    "type": "json"
  },
  {
    "source" : "/i18n/en/docusaurus-plugin-content-docs/current/common/*.mdx",
    "translation" : "/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/common/%original_file_name%",
    "escape_special_characters": 0,
    "ignore": [
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_2clause-bsd-license.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_3clause-bsd-license.mdx.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_account-list.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_add-access-level.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_add-holiday-group.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_add-schedule-item.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_airfob-portal-site-type.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_android-license.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_apache-license.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_biostar-install-steps.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_biostarair-customer-notice.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_boringssl-license.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_bsair-device-info-settings.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_bsair-report-config-note.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_bsx-license-apply.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_bsx-manage-plugins.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_bsx-plugins-usage-example.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_bsx-register-plugin.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_bsx-rollcall.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_bsx-sub-db-create-table-query-mariadb.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_bsx-sub-db-create-table-query-mssql.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_bsx-what-is-plugins.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_cs-fatory-reset.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_device-aux-connection.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_device-connection-standalone-secure-notes.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_device-cs20-di24-aux-connection.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_device-cs20-di24-door-sensor-connection.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_device-cs20-di24-wiegand-connection.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_device-door-control.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_device-door-sensor-connection.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_device-encr10-accessory.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_device-encr10-included-screws.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_device-factory-reset.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_device-indoor-module-relay-connection.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_device-input-connetion.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_device-install-enclosure-battery.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_device-install-enclosure-cs40.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_device-install-enclosure-im120.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_device-install-enclosure-om120.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_device-license-info.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_device-master-admin-settings.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_device-network-connection.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_device-power-connection.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_device-relay-connection.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_device-reset-network-settings.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_device-secure-io2-connection.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_device-standalone-connection.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_device-wiegand-connection-fsf2.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_device-wiegand-connection.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_disclaimers-copyright-notice.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_eclipse-distribution-license.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_eclipse-public-license.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_enroll-credential-mobile-airfob-site-notes.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_enroll-credential-mobile-notes.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_enroll-fingerprint.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_enrolling-face-warning.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_enter-user-page.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_explore-list-pages.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_face-enrollment-authentication-method.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_getting-started-cables-and-connectors.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_gnu-general-public-v2-license.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_gnu-general-public-v3-license.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_gnu-lesser-general-public-v2.1-license.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_gnu-lesser-general-public-v3-license.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_install-note.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_installation-bracket-notes.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_installation-connection-master-slave-info.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_installation-daiod-direction-info.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_installation-intelligent-secure-relay-caution.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_installation-relay-caution.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_ios-license.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_isc-license.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_master-admin-additional-info.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_master-admin-firmware-logic.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_master-admin-support-policy.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_mit-open-source-license.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_openssl-license.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_original-ssleay-license.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_register-device-license.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_register-license-key.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_settings-email-settings.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_sil-open-font-license.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_smart-cardtype.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_sync-with-integ.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_tna-rule-shift-settings.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_usercustomfield.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_usergroupfilter.mdx",
      "/i18n/en/docusaurus-plugin-content-docs/current/common/_zlib-license.mdx",
    ],
    "type": "mdx_v1"
  },
]

# _ce.mdx
# _device-connection-standalone-secure-notes.mdx
# _device-factory-reset.mdx
# _device-input-connetion.mdx
# _device-network-connection.mdx
# _device-relay-connection.mdx
# _device-reset-network-settings.mdx
# _device-secure-io2-connection.mdx
# _device-standalone-connection.mdx
# _device-wiegand-connection.mdx
# _disclaimers-copyright-notice.mdx
# _disclaimers.mdx
# _fcc-compliance-information.mdx
# _getting-started-cables-and-connectors.mdx
# _getting-started-components-note.mdx
# _ic-information.mdx
# _more-information.mdx
# _safety-instructions.mdx