#
# Your Crowdin credentials
#
"project_id" : "4"
"api_token" : "763fcd04f64c1312bad530dba993f905bad244a6d8b0e9f8da39bf8589242e3ee16d864c28f71eeb"
"base_path" : "."
"base_url" : "https://supremainc.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true

#
# Files configuration
#
files: [
  {
    "source" : "/i18n/ko/**/*",
    "translation" : "/i18n/%two_letters_code%/**/%original_file_name%",
    "escape_special_characters": 0,
    "ignore": [
      "i18n/ko/faqs.json",
      "i18n/ko/glossary.json"
    ]
  },
  {
    "source" : "/docs/**/*",
    "translation" : "/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%",
    "escape_special_characters": 0,
    "ignore": [
      "/docs/legal/*.mdx",
      "/docs/_unused/*.mdx",
      "/docs/common/_apache-license.mdx",
      "/docs/common/_gnu-general-public-license.mdx",
      "/docs/common/_gnu-lesser-general-public-license.mdx",
      "/docs/common/_mit-open-source-license.mdx",
      "/docs/common/_more-information.mdx",
      "/docs/common/_openssl-license.mdx",
      "/docs/common/_original-ssleay-license.mdx",
      "/docs/common/_register-device-license.mdx",
      "/docs/common/_sil-open-font-license.mdx",
      "/docs/common/_boringssl-license.mdx",
      "/docs/common/_ios-license.mdx",
      "/docs/common/_android-license.mdx",
      "/docs/common/_airfob-portal-site-type.mdx",
      "/docs/common/_biostarair-customer-notice.mdx",
      "/docs/common/bsx-license/*.mdx",
      "/docs/platform/biostar_x/opensourcelicenses.txt",
      "/docs/platform/biostar_air/**/*.mdx",
      "/docs/how-to/**/*.mdx",
      "/docs/reference/**/*.mdx",
      "/docs/**/**/release-notes/**/*.mdx"
    ]
  }
]