name: Generate PDF Covers

on:
  workflow_dispatch:  # 수동 실행
    inputs:
      title:
        description: '제품 이름'
        required: true
        default: 'BioStation 3'
      subtitle:
        description: '문서 제목'
        required: true
        default: '설치 가이드'
      version:
        description: '버전'
        required: true
        default: '버전 1.08'
      lang:
        description: '언어'
        required: true
        default: '한국어'
      number:
        description: '문서 번호'
        required: true
        default: 'KO 101.00.853'

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install PrinceXML
      run: |
        curl -O https://www.princexml.com/download/prince_15.1-1_ubuntu20.04_amd64.deb
        sudo dpkg -i prince_15.1-1_ubuntu20.04_amd64.deb || true
        sudo apt-get install -f
    
    - name: Make script executable
      run: chmod +x generate-front-cover.sh
    
    - name: Generate PDF with custom parameters
      run: |
        node generate-cover-local.js \
          --title="${{ github.event.inputs.title }}" \
          --subtitle="${{ github.event.inputs.subtitle }}" \
          --version="${{ github.event.inputs.version }}" \
          --lang="${{ github.event.inputs.lang }}" \
          --number="${{ github.event.inputs.number }}" \
          --output="./pdf/front-cover.html"
        
        prince "./pdf/front-cover.html" -o "./pdf/front-cover.pdf"
    
    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v4
      with:
        name: front-cover-pdf
        path: ./pdf/front-cover.pdf
        retention-days: 30
    
    - name: List generated files
      run: |
        echo "Generated files:"
        ls -la ./pdf/
