name: Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Deployment?"
        default: "Suprema"

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Debug Environment Variables
        env:
          REACT_APP_AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          REACT_APP_AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          REACT_APP_REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
        run: |
          echo "REACT_APP_AZURE_CLIENT_ID is set: $([ -n "$REACT_APP_AZURE_CLIENT_ID" ] && echo 'YES' || echo 'NO')"
          echo "REACT_APP_AZURE_TENANT_ID is set: $([ -n "$REACT_APP_AZURE_TENANT_ID" ] && echo 'YES' || echo 'NO')"
          echo "REACT_APP_REDIRECT_URI is set: $([ -n "$REACT_APP_REDIRECT_URI" ] && echo 'YES' || echo 'NO')"
          
      - name: Build website
        env:
          # GitHub Secrets에서 Azure 인증 정보 주입
          REACT_APP_AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          REACT_APP_AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          REACT_APP_REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
        run: yarn build --no-minify
        

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com